INSERT INTO users (first_name,
                   last_name,
                   username,
                   phone_number,
                   email,
                   password,
                   pfp,
                   about,
                   registration_date,
                   status)
VALUES ('Jean',
        'Rakoto',
        'jean.rakoto',
        '+261340000001',
        'jean.rakoto@test.com',
        'test-password-123',
        NULL,
        'Test user from Antananarivo',
        '2026-09-01 09:00:00',
        'ACTIVE'),
       ('Marie',
        'Rasoanaivo',
        'marie.rasoanaivo',
        '+261340000002',
        'marie.rasoanaivo@test.com',
        'test-password-456',
        NULL,
        'Travel enthusiast',
        '2026-09-05 14:30:00',
        'ACTIVE'),
       ('Andry',
        'Rakotomalala',
        'andry.rakotomalala',
        '+261340000003',
        'andry.rakotomalala@test.com',
        'test-password-789',
        NULL,
        'Exploring Madagascar',
        '2026-09-10 10:15:00',
        'ACTIVE'),
       ('Sarah',
        'Randria',
        'sarah.randria',
        '+261340000004',
        'sarah.randria@test.com',
        'test-password-000',
        NULL,
        NULL,
        '2026-09-15 16:45:00',
        'INACTIVE'),
       ('Tiana',
        'Rakotozafy',
        'tiana.rakotozafy',
        '+261340000005',
        'tiana.rakotozafy@test.com',
        '+261340000005',
        NULL,
        'Interested in discovering Madagascar',
        '2026-09-20 08:20:00',
        'ACTIVE');